version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure

  seeder:
    image: siwarakkari/seeder:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - redis

  worker:
    image: siwarakkari/worker:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - PERSIST_DIRECTORY=/app/db
    volumes:
      - worker_db:/app/db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis

volumes:
  redis_data:
  worker_db:
